---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bankcore-config
  namespace: bankcore
data:
  DATABASE_URL:          "postgres://fintech:fintech123@postgres.payflow:5432/bankcore?sslmode=disable"
  REDIS_URL:             "redis.payflow:6379"
  RABBITMQ_URL:          "amqp://fintech:rabbit123@rabbitmq.payflow:5672/"
  TEMPO_ENDPOINT:        "tempo:4317"
  CORE_BANKING_URL:      "http://bankcore-core-banking:8100"
  ACCOUNT_MGMT_URL:      "http://bankcore-account-management:8101"
  TXN_PROCESSING_URL:    "http://bankcore-transaction-processing:8102"
  LOAN_ORIGINATION_URL:  "http://bankcore-loan-origination:8103"
  LOAN_SERVICING_URL:    "http://bankcore-loan-servicing:8104"
  CARD_MGMT_URL:         "http://bankcore-card-management:8105"
  BILL_PAYMENT_URL:      "http://bankcore-bill-payment:8106"
  CUSTOMER_PORTAL_URL:   "http://bankcore-customer-portal:8107"
  REPORTING_URL:         "http://bankcore-reporting-analytics:8108"
  COMPLIANCE_AML_URL:    "http://bankcore-compliance-aml:8109"
  GIN_MODE:              "release"
  LOG_LEVEL:             "info"

---
apiVersion: v1
kind: Secret
metadata:
  name: bankcore-secrets
  namespace: bankcore
type: Opaque
stringData:
  JWT_SECRET:  "bankcore-secret-key-2024"
  DB_PASSWORD: "fintech123"
